# Server settings
server:
  port: 8888
  servlet:
    context-path: /api
  
# SPRING PROFILES
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  oracle-cdr:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.100.23:1521:cdrprd
    username: cdrdev
    password: Bi11ingPrdDB
  oracle-cdr-test:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.100.177:1522:cdrtest
    username: cdr
    password: oracle2019   
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.100.177:3307/report?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456   
  second-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.100.177:3307/xxl_job?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456  
  sqlserver-datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://192.168.201.176:1433;DatabaseName=eBillingForm
    username: ebrm_user
    password: ebrm_user186  
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 1 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 5 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 300000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 10000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  mail:
    host: 202.68.194.227
    username: report-engine@citictel.com
#    password: zou3091172    
    default-encoding: UTF-8
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true   
logging:
  config: classpath:logback.xml
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin.addresses: http://192.168.101.170:8085/xxl-job-admin,http://192.168.101.171:8085/xxl-job-admin
### xxl-job executor address
    executor.appname: report-engine-executor
    executor.ip: 
    executor.port: 9999
    accessToken:
    executor.logpath: /data/report-engine-job/jobhandler
### xxl-job log retention days
    executor.logretentiondays: -1  
httpclient:
    connecttimeout: 5000
    readtimeout: 60000 
  
