# Server settings
server:
  port: 8888
  servlet:
    context-path: /api
  
# SPRING PROFILES
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.100.177:3307/report?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456   
  second-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.100.177:3307/xxl_job?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456 
  mail:
    host: 202.68.194.227
    username: report-engine-test@citictel.com
#    password: zou3091172    
    default-encoding: UTF-8
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true   
logging:
  config: classpath:logback.xml
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin.addresses: http://192.168.100.177:8085/xxl-job-admin,http://192.168.101.231:8085/xxl-job-admin
### xxl-job executor address
    executor.appname: report-engine-executor
    executor.ip: 
    executor.port: 9998
    accessToken:
    executor.logpath: /tmp/report-engine-job/jobhandler
### xxl-job log retention days
    executor.logretentiondays: -1  
  
  